### ISSUE TITLE
Projektit ei lataudu / aukea

### ISSUE THREAD

**Issue by vepemustonen** [rage/ohjelmointi-20#32]
Aloin aamulla tekemään osan 3 harjoituksia, mutta netbeans ei avannut projekteja. Ohjelma antaa ilmoituksen: There are 32 excercises that are downloaded but not openened. Kun klikkaan ilmoitusta ja yritän avata harjoitukset, heittää netbeans unexpexted exceptionin näillä spekseillä:

java.lang.IllegalArgumentException: Key contains code point U+0000
	at java.prefs/java.util.prefs.AbstractPreferences.get(AbstractPreferences.java:296)
	at org.netbeans.modules.maven.queries.MavenFileOwnerQueryImpl.registerCoordinates(MavenFileOwnerQueryImpl.java:153)
	at org.netbeans.modules.maven.ProjectOpenedHookImpl.registerWithSubmodules(ProjectOpenedHookImpl.java:431)
	at org.netbeans.modules.maven.ProjectOpenedHookImpl.projectOpened(ProjectOpenedHookImpl.java:138)
	at org.netbeans.spi.project.ui.ProjectOpenedHook$1.projectOpened(ProjectOpenedHook.java:60)
[catch] at org.netbeans.modules.project.ui.OpenProjectList.notifyOpened(OpenProjectList.java:1273)
	at org.netbeans.modules.project.ui.OpenProjectList.doOpenProject(OpenProjectList.java:1354)
	at org.netbeans.modules.project.ui.OpenProjectList.open(OpenProjectList.java:798)
	at org.netbeans.modules.project.ui.OpenProjectList$6.run(OpenProjectList.java:650)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)

**Comment by vepemustonen** [comment]
Ongelma ei poistu, vaikka päivittää kaikki plugarit yms tai asentaa netbeansin uudelleen. Tämähän tosiaan estää sekä tehtävien tekemisen, että palauttamisen tällä hetkellä. Kyrsii suht paljon, kun varasin tätä varten vapaapäivän töistä :)

**Comment by nygrenh** [comment]
Toi näyttäisi kaatuvan asetusten hakemiseen. Muuta tosta ei tule mieleen kuin että asetuksissa olisi jotakin korruptoitunut. Voit kokeilla korjaantuuko toi Netbeanssin asetusten poistolla: https://ohjelmointi-20.mooc.fi/netbeansin-asetusten-poisto

**Comment by vepemustonen** [comment]
Tää toimi. Kiitoksia!
