### ISSUE TITLE
Ei oo mahdollista ladata tehtavia TMCiin

### ISSUE THREAD

**Issue by arswift** [rage/ohjelmointi-20#72]
Kun yritän ladata tehtavia, saan viestin virheestä.
"ava.lang.RuntimeException: Failed to open project for exercise osa01-Osa01_33.Tunnussana
[catch] at fi.helsinki.cs.tmc.actions.DownloadExercisesAction$1.bgTaskReady(DownloadExercisesAction.java:82)
	at fi.helsinki.cs.tmc.actions.DownloadExercisesAction$1.bgTaskReady(DownloadExercisesAction.java:69)
	at fi.helsinki.cs.tmc.utilities.BgTask.call(BgTask.java:173)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
<img width="960" alt="virhe" src="https://user-images.githubusercontent.com/40257907/79747005-9d021c80-8313-11ea-8590-03664c9077b5.png">
"

**Comment by arswift** [comment]
Olen löytänyt ratkaisen tällä: https://www.reddit.com/r/learnjava/comments/enpj12/trouble_getting_the_2020_mooc_course_to_run_on/
